//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.17 at 07:44:53 PM PST 
//


package edu.stevens.cs548.clinic.service.dto.provider;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import edu.stevens.cs548.clinic.service.dto.treatment.ProviderDto;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.stevens.cs548.clinic.service.dto.provider package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Specialization_QNAME = new QName("http://cs548.stevens.edu/clinic/schemas/provider", "specialization");
    private final static QName _ProviderDto_QNAME = new QName("http://cs548.stevens.edu/clinic/schemas/provider", "provider-dto");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.stevens.cs548.clinic.service.dto.provider
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProviderDto }
     * 
     */
    public ProviderDto createProviderDTO() {
        return new ProviderDto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecializationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cs548.stevens.edu/clinic/schemas/provider", name = "specialization")
    public JAXBElement<SpecializationType> createSpecialization(SpecializationType value) {
        return new JAXBElement<SpecializationType>(_Specialization_QNAME, SpecializationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProviderDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cs548.stevens.edu/clinic/schemas/provider", name = "provider-dto")
    public JAXBElement<ProviderDto> createProviderDto(ProviderDto value) {
        return new JAXBElement<ProviderDto>(_ProviderDto_QNAME, ProviderDto.class, null, value);
    }
}
